name: Build Wheels

on:
  push:
    branches: ['master', 'develop']
    tags: 'v*.*.*'

jobs:
  Build-Wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-latest, ubuntu-24.04-arm, windows-latest]
        archs: [auto64]

    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade-strategy eager --upgrade cython twine cibuildwheel~=2.0 build

    - name: Build Tarball
      # Only one out of the OS matrix needs to upload the tarball.
      if: matrix.os == 'ubuntu-latest'
      run: python3 -m build --sdist

    - name: Build Wheels
      env:
        CIBW_ARCHS: ${{ matrix.archs }}
        CIBW_ENABLE: pypy
        CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux-image }}
      run: python -m cibuildwheel --output-dir dist

    - name: Check Wheels
      shell: bash
      run: |
        twine check dist/*
        test -f dist/*abi3* && abi3
        # https://blog.trailofbits.com/2022/11/15/python-wheels-abi-abi3audit/
        abi3audit dist/*.whl

    - uses: actions/upload-artifact@v4
      # Upload some wheels for manual inspection. We don't need all of them.
      if: matrix.os == 'ubuntu-latest'
      with:
        name: Linux x86-64 CPython Wheels
        path: "dist/*.whl"

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: twine upload --skip-existing -u __token__ dist/*
