name: Build Wheels

on:
  push:
    branches: ['master', 'develop']
    tags: 'v*.*.*'

jobs:
  Build-Wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-latest, windows-latest]
        archs: [auto64]

    env:
      MACOSX_DEPLOYMENT_TARGET: "10.14"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade-strategy eager --upgrade cython twine cibuildwheel build

    - name: Build Tarball
      # Only one out of the OS matrix needs to upload the tarball.
      if: matrix.os == 'ubuntu-latest'
      run: python3 -m build --sdist

    - name: Build Wheels
      env:
        CIBW_ARCHS: ${{ matrix.archs }}
        CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux-image }}
      run: python -m cibuildwheel --output-dir dist

    - name: Check Wheels
      run: twine check dist/*

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: twine upload --skip-existing -u __token__ dist/*
